from pydantic import BaseModel, UUID4, Field
from typing import Annotated
from sqlalchemy import DateTime
from datetime import datetime

class BaseSchema(BaseModel):
    class Config:
        # Forbid extra fields to be added in the input data
        # From_attributes allows reading data from ORM models directly -> ORM models are ? // serves to make conversions from model to schema / schema to model
        extra = "forbid"
        from_attributes = True

# To add fields that are not to be provided by the user but are generated by the system, like IDs
class OutMixin(BaseModel):
    id: Annotated[UUID4, Field(description="Unique identifier") ]
    created_at: Annotated[datetime, Field(description="Record creation timestamp")]